### ISSUE TITLE
Wrong file path format 

### ISSUE THREAD

**Issue by tboerger** [fortissimo1997/simplecov-lcov#17]
I really like this gem in combination with aircover.co, but your generated path is invalid because the LCOV specification says you have to use absolute paths. You are overwriting this with ./ at https://github.com/fortissimo1997/simplecov-lcov/blob/master/lib/simplecov-lcov.rb#L72

How can we fix that?

**Comment by marceldegraaf** [comment]
Running into this problem too. See [this issue](https://github.com/drone-plugins/drone-coverage/issues/5) on the Aircover tracker for more info.

**Comment by tboerger** [comment]
> Running into this problem too. See this issue on the Aircover tracker for more info.

I have opened this issue because of that, I'm part of the Drone team ;)

**Comment by marceldegraaf** [comment]
Oh, heh, I hadn't noticed that. Thanks ;-)

**Comment by jmccann** [comment]
Seems this was just broke recently by https://github.com/fortissimo1997/simplecov-lcov/commit/f14856c0874922103338b272fe81e9be7d705add

**Comment by RepoCorp** [comment]
@fortissimo1997 my application can't find the project files because the generated LCOV single file uses relative paths. I thought it was fixed in #21 but I don't see how. I'm still getting relative paths, I guess because of the `filename = file.filename.gsub("#{SimpleCov.root}/", './')`
