### ISSUE TITLE
Compatibility with branch coverage

### ISSUE THREAD

**Issue by GCorbel** [fortissimo1997/simplecov-lcov#23]
Simplecov 0.18 added the coverage for branches : https://github.com/colszowka/simplecov#branch-coverage-ruby--25. It works with the HTML formatted but not with simplecov-lcov. It would be nice to have it too.

**Comment by drdrsh** [comment]
I have a PR to add that feature. Could use some eyes on it.
https://github.com/fortissimo1997/simplecov-lcov/pull/24

**Comment by GCorbel** [comment]
I checked and it works. There is information in the lcov file. Sadly, it's a bit useless for me at the moment because I use undercover and it's not compatible. I saw there is this issue : https://github.com/grodowski/undercover/issues/26 but it has been closed.

I'm probably not the best person to review the MR but I checked the code and it looks correct.

Thanks a lot.

**Comment by drdrsh** [comment]
@GCorbel The PR was merged and @fortissimo1997 released version 0.8.0 which includes that change. I think we can close this issue.

**Comment by GCorbel** [comment]
Thanks a lot.
